steps:
- id: 'terraform build'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
        cd env/prod
        
        echo "Running initialisation..."
        terraform init

        echo "Validating code..."
        terraform validate

        echo "planning config..."
        terraform plan -out webapp.plan

        echo "Applying config..."
        terraform apply -auto-approve webapp.plan
